project:
  type: website
  output-dir: docs
  preview: 
    watch-inputs: false
  render:
    - index.qmd
    - historical.qmd
    - recent.qmd
    - risk.qmd

website:
  title: "Northwoods Fire Assessment"
  navbar:
    search: TRUE
    pinned: true
    left:
      - href: index.qmd
        text: Home
        
      - href: historical.qmd
        text: Historical context
        
      - href: recent.qmd
        text: Recent fires
        
      - href: risk.qmd
        text: Current risk



      
format:
  html:
    page-layout: full
    theme: 
      light: flatly
      dark: darkly
      
    css: styles.css
    toc: true
    toc-depth: 3
    toc-expand: 3
    
editor: source
